schema: https://rickandmortyapi.com/graphql
documents: src/graphql/**/*.{gql,graphql}

extensions:
  codegen:
    overwrite: true
    schema: https://rickandmortyapi.com/graphql
    documents: src/graphql/**/*.{gql,graphql}
    generates:
      src/graphql/generated.ts:
        plugins:
          - typescript
          - typescript-operations
          - typescript-graphql-request
        config:
          gqlImport: graphql-request#gql
          dedupeFragments: true
          pureMagicComment: true
          useTypeImports: true

      src/graphql/generic.ts:
        plugins:
          - typescript
          - typescript-operations
          - typescript-generic-sdk
        config:
          documentNodeImport: ./document-node#DocumentNode
          optimizeDocumentNode: false
          gqlImport: ./gql#gql
          dedupeFragments: true
          pureMagicComment: true
          useTypeImports: true