schema: https://rickandmortyapi.com/graphql
documents: src/graphql/**/*.{gql,graphql}

extensions:
  codegen:
    schema: https://rickandmortyapi.com/graphql
    documents: src/graphql/**/*.{gql,graphql}
    generates:
      src/graphql/generated.ts:
        plugins:
          - typescript
          - typescript-operations
          - typescript-graphql-request
        config:
          gqlImport: graphql-request#gql