import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { type RelayProps, withRelay } from "relay-nextjs";
import {
  Card,
  Container,
  LoadingOverlay,
  SimpleGrid,
  Text,
} from "@mantine/core";

import { getClientEnvironment } from "~/lib/relay_client_environment";
import Expisodes, { EpisodesQuery } from "~/components/episodes";
import { Suspense } from "react";

const HomePage: NextPage<RelayProps<{}, any>> = ({ preloadedQuery, CSN }) => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Suspense>
        <Expisodes preloadedQuery={preloadedQuery} CSN={CSN} />
      </Suspense>
    </Container>
  );
};
// export default HomePage;
export default withRelay(HomePage, EpisodesQuery, {
  // Fallback to render while the page is loading.
  // This property is optional.
  // fallback: <LoadingOverlay visible />,
  // Create a Relay environment on the client-side.
  // Note: This function must always return the same value.
  createClientEnvironment: () => getClientEnvironment()!,
  // to this function.
  createServerEnvironment: async (ctx) => {
    const { createServerEnvironment } = await import(
      "~/lib/server/relay_server_environment"
    );
    return createServerEnvironment();
  },
});
