query CharacterPages {
  characters {
    info {
      pages
    }
  }
}

query Characters($page: Int = 1) {
  characters(page: $page) {
    info {
      count
      pages
    }
    results {
      ...EpisodeCharactersFrag
    }
  }
}

query CharacterById($id: ID!) {
  character(id: $id) {
    ...EpisodeCharactersFrag
    status
    species
    type
    gender
    created
    origin {
      ...LocationFrag
    }
    location {
      ...LocationFrag
    }
    episode {
      ...EpisodeFrag
    }
  }
}

query CharactersId {
  characters {
    results {
      id
    }
  }
}
